---
abstract: "it's easy to include data with a CPAN module"
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Include-Data
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006000
resources:
  bugtracker: https://github.com/benkasminbullock/Acme-Include-Data/issues
  repository: git://github.com/benkasminbullock/Acme-Include-Data.git
version: 0.03
